Add UI/UX maket
TSI-Projects/group-project pull request #3
Opened 2024-09-15 15:34 UTC by DevalordDevalis

2024-09-17 16:07 UTC, AndrejsPon00 approved these changes, later dismissed

2024-09-19 15:38 UTC, SkinonikS requested changes
Удалить пробелы между строчками в README.md

2024-09-22 13:57 UTC, AndrejsPon00 submitted a review, later dismissed

2024-09-23 10:19 UTC, narcisiwe reviewed
Можешь перепроверить нр. картинок, верно ли указаны переходы и ссылки на картинки?

2024-09-23 10:19 UTC, narcisiwe commented on UX_UI/README.md
> +При нажатии кнопки "создать заказ" окно с главным меню скрывается и нам открывается новое окно, картинка под номером 8.
Скорее всего имелось ввиду карти нка под нр.7

2024-09-23 10:19 UTC, narcisiwe commented on UX_UI/README.md
> +При нажатии кнопки "действующие заказы" окно с главным меню скрывается и нам открывается новое окно, картинка под номером 7.
Скорее всего имелось ввиду карти нка под нр.6

2024-09-23 10:19 UTC, narcisiwe commented on UX_UI/README.md
> +При нажатии кнопки "выполенные заказы" окно с главным меню скрывается и нам открывается новое окно, картинка под номером 7.
Скорее всего имелось ввиду карти нка под нр.6

2024-09-23 10:19 UTC, narcisiwe commented on UX_UI/README.md
> +Так же присутвуствует сверху слева кнопка в виде шестерёнки, при нажатии которой скрывается окно с главным меню и переводит на страницу авторизации, картинка под номером 3.
Может лучше "домик", шестеренка это обычно про настройки. Тоже видимо не верный нр. картинки, авторизаця под 1ым нр. Тогда выходит при нажатии на "домик/шестеренку" делаем логаут, раз на страницу авторизхации переводим?

2024-09-23 10:19 UTC, narcisiwe commented on UX_UI/README.md
> +Попав в окно  "Меню"  можно увидеть 3 кнопки.
А как мы собственно сюда поподаем? Или в предыдущем пункте речь шла про про эту страницу "авторизации". Не будет ли резонно объеденить 2 и 3ию картинки. Так как они в целом просто ссылки на другие страницы? Слева заказы, справа сотрудники?

2024-09-23 10:19 UTC, narcisiwe commented on UX_UI/README.md
> +Кнопка "Карандашик" справа от сторки записи, при нажатии на него можно вносить изменения в строку записи и далее нажав на зелёную галочку отсылаются изменённые данные в БД.
Думаю было бы рациональнее, просто нажимая кнопку создать заказ, открывается пустая форма, где мжно внести данные и записать заказ (типа рис.7). И При нажати на карандаш, вызываем эту же форму, но уже с данными из БД. Но чтобы не затягивать, сделоаем как есть, просто сейчас что то мысля такая посетила

2024-09-25 16:05 UTC, DevalordDevalis commented on UX_UI/README.md
> +Кнопка "Карандашик" справа от сторки записи, при нажатии на него можно вносить изменения в строку записи и далее нажав на зелёную галочку отсылаются изменённые данные в БД.
Исправил

2024-09-28 06:40 UTC, narcisiwe approved these changes, later dismissed

2024-10-01 16:08 UTC, AndrejsPon00 approved these changes, later dismissed

2024-10-18 18:01 UTC, SkinonikS approved these changes

2024-10-19 09:34 UTC, merged